### ISSUE TITLE
Support HTML Imports

### ISSUE THREAD

**Issue by cdata** [cloudflare/collapsify#17]
[HTML Imports](http://www.w3.org/TR/html-imports/) are an emerging standard that enable authors to import document fragments similarly to how CSS is imported today. It would be cool if Collapsify supported inlining HTML Imports in a sane way. For reference, another project that already makes some attempts to do this is [Vulcanize](https://github.com/Polymer/vulcanize).

**Comment by RReverser** [comment]
HTML Imports never got significant adoption, so I guess we can close this issue at this point.
