### ISSUE TITLE
Support for defined excludes for inlining

### ISSUE THREAD

**Issue by gpearce** [cloudflare/collapsify#50]
As an Enterprise customer we ran across a valid issue within our particular use case today - where you may wish for a Cloudflare Error Page (all run via collapsify) to *not* inline a particular image, CSS file, or script on _some_ error pages.

It'd be awesome if it was possible to wrap exclude tags around content you wish to prevent from being inlined.

```
<!-- {INLINE-DISABLE} -->
<link rel="stylesheet" href="/path/to/style.css">
<img src="/path/to/img.png">
<!-- {INLINE-ENABLE} -->
```

**Comment by cascadingstyletrees** [comment]
I think this is intended, as Cloudflare error pages are downloaded, and live in the Cloudflare system, none of the content will be served from third party resources.

**Comment by sgoo** [comment]
Thanks for the issue, but we are unlikely to address feature requests for Collapsify through Github issues.
If you want this or other feature improvements please start a discussion on community.cloudflare.com or raise a support request and it will find its way to the people who prioritize these things.
